import Head from 'next/head'
import { Inter, Roboto_Flex } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import Home from './components/Home'
export default function Index() {  
  return (
    <>
      <Head>
        <title>Youtube Transcript Summarizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/youtube.svg" />
      </Head>
      <main >
         <Home/>
      </main>
    </>
  )
}
